# Generated by Django 5.2.17 on 2026-08-21 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('existencia', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='producto.producto')),
            ],
            options={
                'db_table': 'inventario',
                'ordering': ['producto__nombre'],
            },
        ),
    ]
