# Generated by Django 5.2.17 on 2026-08-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_detallecompra'),
        ('empleado', '0002_alter_empleado_email_alter_empleado_telefono'),
        ('inventario', '0001_initial'),
        ('producto', '0001_initial'),
        ('venta', '0002_alter_venta_estado_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('entrada_reversa', 'Entrada reversa'), ('salida_reversa', 'Salida reversa')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('revertido', 'Revertido')], default='activo', max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='compra.detallecompra')),
                ('detalle_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='venta.detalleventa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='empleado.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='producto.producto')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
